application: spaghetti-night
version: 1
runtime: go
api_version: go1

handlers:
- url: /app/admin/.*
  script: _go_app
  login: admin

- url: /app/.*
  script: _go_app

- url: /$
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static
